### PR TITLE
"Collection" to "Decks", re-position import button, button CSS styling, export & import deck implementation

### PR DESCRIPTION
**Pull request by stephencapper**
Change "Collections" to "Decks" in navbar, move import deck button out of each deck and clean up button css a little

### CODE REVIEW

**Comment by stephencapper** [comment]
[Update references to "Collections" to "Decks" on page](https://trello.com/c/v4bPRkhk/89-update-references-to-collections-to-decks-on-page)

**Comment by stephencapper** [comment]
Also finalized export deck function and linked to export deck function, and validated working correctly in local machine, first three tasks in checklist in implementation ticket 5.3.4.0.2

**Comment by stephencapper** [comment]
[Stephen - Implementation 5.3.4.0.2 : Deck Selection page import and export functionality](https://trello.com/c/YNAGTWV6/64-stephen-implementation-53402-deck-selection-page-import-and-export-functionality)

**Comment by stephencapper** [comment]
Completed remaining functionality for import deck - including connecting to button and checking worked as expected in local instance - see linked implementation task for full details.

**Comment by stephencapper** [comment]
[[TBD] Implementation 5.3.4.1 : Deck Selection page import and export buttons](https://trello.com/c/KplUFYow/65-tbd-implementation-5341-deck-selection-page-import-and-export-buttons)

**Review by JamesClover — APPROVED** [review]
looks great! excited to see this functionality!

**Pull request merged**
